### ISSUE TITLE
Getting an issue when importing - dial tcp 138.201.205.233:443: connect: connection refused

### ISSUE THREAD

**Issue by sharathkumar13** [trimmer-io/go-csv#1]
Hi, 

I'm getting the below when doing dep ensure. 

![image](https://user-images.githubusercontent.com/29590471/85294195-f7f2f400-b4bb-11ea-8093-807dd7634062.png)

What could be the issue?. This was working previoulsy, but not now.

**Comment by echa** [comment]
Unintended side effect. We were working on the server. Should be back up again.

**Comment by sharathkumar13** [comment]
Thank you @echa. It worked now.
